In [1]:
pip install gspread -q

Note: you may need to restart the kernel to use updated packages.

In [2]:
import json
import pandas as pd
import numpy as np
from metabase_query import Metabase

In [3]:
# Initialize the MetabaseQuery object
mb = Metabase(metabase_session='7a113f35-13a7-4d8b-83be-8a07cacfa253')

In [4]:
url = 'https://metabase.vitlamdata.com/question/49285-m05-k01'
data = mb.query(url=url, format='json')

Parsing URL and verifying Metabase Session 1
Querying 1...
Received data 1

In [5]:
df = pd.json_normalize(data)

In [12]:
for i in set(df.customer_source):
    print(i)

Affiliate
Facebook
Organic
Twitter
Google

In [15]:
df['created_at'] = pd.to_datetime(df['created_at'], utc=True, format='ISO8601')

In [17]:
for col in df.select_dtypes(include=["datetime64[ns, UTC]", "datetime64[ns]"]):
            df[col] = df[col].dt.strftime("%Y-%m-%d %H:%M:%S")

In [18]:
MIN_DATE = df["created_at"].min()
MAX_DATE = df["created_at"].max()
print(MIN_DATE, MAX_DATE)

2016-04-30 18:56:13 2020-04-19 14:07:15

In [ ]:
df.head()

,sales_id,created_at,quantity,gross_sales,tax,net_sales,product_id,product_name,category,customer_id,customer_name,customer_city,customer_state,customer_source
0,1,Unknown,2,53.070299,5.307030,47.763269,14,Awesome Concrete Shoes,Widget,1,Hudson Borer,Wood River,NE,Twitter
1,2,Unknown,3,240.249662,24.024966,216.224696,123,Mediocre Wooden Bench,Gizmo,1,Hudson Borer,Wood River,NE,Twitter
2,3,Unknown,2,71.788364,6.537168,58.834516,105,Fantastic Wool Shirt,Gadget,1,Hudson Borer,Wood River,NE,Twitter
3,4,Unknown,6,460.024717,46.002472,414.022245,94,Awesome Bronze Plate,Widget,1,Hudson Borer,Wood River,NE,Twitter
4,5,Unknown,5,448.766225,44.876623,403.889603,132,Sleek Steel Table,Widget,1,Hudson Borer,Wood River,NE,Twitter

In [ ]:
df.tail()

,sales_id,created_at,quantity,gross_sales,tax,net_sales,product_id,product_name,category,customer_id,customer_name,customer_city,customer_state,customer_source
18755,18756,2018-09-07T23:05:20.186+07:00,4,106.867072,10.686707,96.180364,165,Aerodynamic Copper Knife,Gizmo,2499,Cloyd Beer,Spokane,WA,Twitter
18756,18757,2018-12-13T15:54:11.721+07:00,2,163.347417,16.334742,147.012675,131,Practical Aluminum Coat,Widget,2499,Cloyd Beer,Spokane,WA,Twitter
18757,18758,2018-08-10T18:18:20.444+07:00,7,689.627638,68.962764,620.664874,127,Practical Bronze Watch,Widget,2499,Cloyd Beer,Spokane,WA,Twitter
18758,18759,2019-12-25T16:40:29.152+07:00,2,169.324387,16.932439,152.391948,45,Sleek Wool Wallet,Doohickey,2500,Kenny Schmidt,Verona,KY,Google
18759,18760,2020-03-28T17:12:06.681+07:00,1,78.767254,7.876725,70.890529,138,Incredible Plastic Watch,Doohickey,2500,Kenny Schmidt,Verona,KY,Google

In [ ]:
df.dtypes

sales_id             int64
created_at             str
quantity             int64
gross_sales        float64
tax                float64
net_sales          float64
product_id           int64
product_name           str
category               str
customer_id          int64
customer_name          str
customer_city          str
customer_state         str
customer_source        str
dtype: object

In [ ]:
import gspread

gc = gspread.service_account(filename="D:\DKSH\metabase_project\src\metabase_project\configs\key.json")

<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_27044\3365528144.py:3: SyntaxWarning: invalid escape sequence '\D'
  gc = gspread.service_account(filename="D:\DKSH\metabase_project\src\metabase_project\configs\key.json")

In [ ]:
GDATA = gc.open_by_key('139VrY0tzOXxmmMhZflIq07M-qAh5zeo7O-F1LijfjME')

In [ ]:
METABASE_GSHEET= GDATA.worksheet('Sheet1')

In [ ]:
METABASE_GSHEET.clear()
METABASE_GSHEET.update([df.columns.values.tolist()] + df.values.tolist())

{'spreadsheetId': '139VrY0tzOXxmmMhZflIq07M-qAh5zeo7O-F1LijfjME',
 'updatedRange': 'Sheet1!A1:N18761',
 'updatedRows': 18761,
 'updatedColumns': 14,
 'updatedCells': 262654}

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_id         18760 non-null  int64
 1   created_at       18738 non-null  str
 2   quantity         18760 non-null  int64
 3   gross_sales      18760 non-null  float64
 4   tax              18760 non-null  float64
 5   net_sales        18760 non-null  float64
 6   product_id       18760 non-null  int64
 7   product_name     18760 non-null  str
 8   category         18760 non-null  str
 9   customer_id      18760 non-null  int64
 10  customer_name    18760 non-null  str
 11  customer_city    18760 non-null  str
 12  customer_state   18760 non-null  str
 13  customer_source  18760 non-null  str
dtypes: float64(3), int64(4), str(7)
memory usage: 2.0 MB

In [ ]:
df.tail()

,sales_id,created_at,quantity,gross_sales,tax,net_sales,product_id,product_name,category,customer_id,customer_name,customer_city,customer_state,customer_source
18755,18756,2018-09-07T23:05:20.186+07:00,4,106.867072,10.686707,96.180364,165,Aerodynamic Copper Knife,Gizmo,2499,Cloyd Beer,Spokane,WA,Twitter
18756,18757,2018-12-13T15:54:11.721+07:00,2,163.347417,16.334742,147.012675,131,Practical Aluminum Coat,Widget,2499,Cloyd Beer,Spokane,WA,Twitter
18757,18758,2018-08-10T18:18:20.444+07:00,7,689.627638,68.962764,620.664874,127,Practical Bronze Watch,Widget,2499,Cloyd Beer,Spokane,WA,Twitter
18758,18759,2019-12-25T16:40:29.152+07:00,2,169.324387,16.932439,152.391948,45,Sleek Wool Wallet,Doohickey,2500,Kenny Schmidt,Verona,KY,Google
18759,18760,2020-03-28T17:12:06.681+07:00,1,78.767254,7.876725,70.890529,138,Incredible Plastic Watch,Doohickey,2500,Kenny Schmidt,Verona,KY,Google

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_id         18760 non-null  int64
 1   created_at       18738 non-null  str
 2   quantity         18760 non-null  int64
 3   gross_sales      18760 non-null  float64
 4   tax              18760 non-null  float64
 5   net_sales        18760 non-null  float64
 6   product_id       18760 non-null  int64
 7   product_name     18760 non-null  str
 8   category         18760 non-null  str
 9   customer_id      18760 non-null  int64
 10  customer_name    18760 non-null  str
 11  customer_city    18760 non-null  str
 12  customer_state   18760 non-null  str
 13  customer_source  18760 non-null  str
dtypes: float64(3), int64(4), str(7)
memory usage: 2.0 MB

In [ ]:
df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
for col in df.select_dtypes(include=["datetime64[ns, UTC]", "datetime64[ns]"]):
    df[col] = df[col].dt.strftime("%Y-%m-%d %H:%M:%S")
    df[col]=df[col].fillna("Unknown")

ValueError: time data "Unknown" doesn't match format "%Y-%m-%d %H:%M:%S". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
# df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_id         18760 non-null  int64
 1   created_at       18760 non-null  str
 2   quantity         18760 non-null  int64
 3   gross_sales      18760 non-null  float64
 4   tax              18760 non-null  float64
 5   net_sales        18760 non-null  float64
 6   product_id       18760 non-null  int64
 7   product_name     18760 non-null  str
 8   category         18760 non-null  str
 9   customer_id      18760 non-null  int64
 10  customer_name    18760 non-null  str
 11  customer_city    18760 non-null  str
 12  customer_state   18760 non-null  str
 13  customer_source  18760 non-null  str
dtypes: float64(3), int64(4), str(7)
memory usage: 2.0 MB

In [ ]:
df["created_at"] = pd.to_datetime(df["created_at"], utc=True, errors = 'coerce')

In [ ]:
df.created_at.min()

Timestamp('2016-04-30 18:56:13+0000', tz='UTC')

In [ ]:
df.head()

,sales_id,created_at,quantity,gross_sales,tax,net_sales,product_id,product_name,category,customer_id,customer_name,customer_city,customer_state,customer_source
0,1,2019-02-11 21:40:27+00:00,2,53.070299,5.307030,47.763269,14,Awesome Concrete Shoes,Widget,1,Hudson Borer,Wood River,NE,Twitter
1,2,2018-05-15 08:04:04+00:00,3,240.249662,24.024966,216.224696,123,Mediocre Wooden Bench,Gizmo,1,Hudson Borer,Wood River,NE,Twitter
2,3,2019-12-06 22:22:48+00:00,2,71.788364,6.537168,58.834516,105,Fantastic Wool Shirt,Gadget,1,Hudson Borer,Wood River,NE,Twitter
3,4,2019-08-22 16:30:42+00:00,6,460.024717,46.002472,414.022245,94,Awesome Bronze Plate,Widget,1,Hudson Borer,Wood River,NE,Twitter
4,5,2018-10-10 03:34:47+00:00,5,448.766225,44.876623,403.889603,132,Sleek Steel Table,Widget,1,Hudson Borer,Wood River,NE,Twitter